version: 2.1

jobs:
  build:
    docker:
      - image: cimg/php:8.2.5
    working_directory: ~/d10
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "1d:25:dc:ac:34:51:2d:48:97:6f:54:ae:ef:99:49:b4"
      - run:
          shell: /bin/sh
          command: |
            composer install
            pwd
      - run:
          shell: /bin/sh
          command: |
            cd ../.
            git checkout git@github.com:marvoey/d10-artifact.git
            echo "ls -al d10-artifact"
            ls -al d10-artifact
