version: 2.1

jobs:
  build:
    docker:
      - image: cimg/php:8.2.5
    steps:
      - checkout
      - run:
          command: |
            php --version
      - run:
          shell: /bin/sh
          command: |
            composer install
            mkdir deploy
            cp -r .git deploy
            cd deploy
            ls -al
            git checkout .
            ls -al
