version: 2.1

jobs:
  build:
    docker:
      - image: cimg/php:8.2.5
    steps:
      - checkout
      - run:
          command: |
            php --version
      - run:
          shell: /bin/sh
          command: |
            composer install
            mkdir deploy
            cp -r .git deploy
            cd deploy
            echo "pwd"
            pwd
            ls -al
            git checkout .
            echo "git checkout ."
            echo "ls -al"
            ls -al
      - run:
          shell: /bin/sh
          command: |
            cd deploy
            pwd
            composer install
            echo "ls -al"
            ls -al
      - add_ssh_keys:
            fingerprints:
              - "1d:25:dc:ac:34:51:2d:48:97:6f:54:ae:ef:99:49:b4"
      - run:
          shell: /bin/sh
          command: |
            cd deploy
            pwd
            git config --global user.email "marvoey99@gmail.com"
            git config --global user.name "Marvin Oey (CircleCI Build)"
            rm -rf .gitignore
            git remote add artifact git@github.com:marvoey/d10-artifact.git
            git fetch --all
            git add .
            git commit -m "Deploy artifact"
            git log
            git push -u artifact main
       

       
