version: 2.1

jobs:
  build:
    docker:
      - image: cimg/php:8.2.5
    steps:
      - checkout
      - run: php --version
      - run: ls -al
      - run: composer install
      - run: ls -al
      - run: mkdir deploy
      - run: cp -r .git deploy
      - run: ls -al deploy
      - run: cd ./deploy
      - run: pwd
      - run: ls deploy
